### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by dinnersticks** [riverbed/steelscript#1]
Any help appreciated. 

= Error  =
Python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    pcap.info()
  File "C:\Python27\lib\site-packages\steelscript\wireshark\core\pcap.py", line
42, in info
    capinfos = subprocess.check_output(cmd)
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

= Script =
steelscript.wireshark.core.pcap import PcapFile

pcap = PcapFile('\windowspath\pcapnamehere.pcap')
pcap.info()
print pcap.starttime
print pcap.endtime
print pcap.numpackets

= Packages =
steel about

Installed SteelScript Packages
Core packages:
  steelscript                               0.9.7
  steelscript.netprofiler                   0.9.5
  steelscript.netshark                      0.9.5
  steelscript.wireshark                     0.9.4.1

Application Framework packages:
  steelscript.appfwk                        0.9.8.2

Paths to source:
  C:\Python27\lib\site-packages

**Comment by mgarabed** [comment]
@dinnersticks can you confirm that your Windows path includes the location of the following Wireshark executables:
capinfos
editcap
tshark

We need to have some better configuration included here, but right now the script will just try to run those commands directly.

**Comment by mgarabed** [comment]
Closing due to inactivity.  If you have additional info, please post.
