### ISSUE TITLE
Issue with pkg_resources when building steelscript

### ISSUE THREAD

**Issue by gwenblum** [riverbed/steelscript#32]
=> ERROR [3/4] RUN set -ex         && steel mkworkspace -d /root/steelscript-workspace                      0.7s
------
 > [3/4] RUN set -ex         && steel mkworkspace -d /root/steelscript-workspace:
#0 0.526 + steel mkworkspace -d /root/steelscript-workspace
#0 0.631 Traceback (most recent call last):
#0 0.631   File "/usr/local/bin/steel", line 5, in <module>
#0 0.632     from steelscript.commands.steel import run
#0 0.632   File "/src/steelscript/steelscript/__init__.py", line 1, in <module>
#0 0.632     __import__("pkg_resources").declare_namespace(__name__)
#0 0.632     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 0.632 ModuleNotFoundError: No module named 'pkg_resources'
------
Dockerfile:28
--------------------
  27 |
  28 | >>> RUN set -ex \
  29 | >>>         && steel mkworkspace -d /root/steelscript-workspace
  30 |
--------------------
ERROR: failed to solve: process "/bin/sh -c set -ex         && steel mkworkspace -d /root/steelscript-workspace" did not complete successfully: exit code: 1
timed out waiting for input: auto-logout

**Comment by gwenblum** [comment]
Because the container image python 3.12 does not include setuptools anymore (https://github.com/docker-library/python/pull/954) we need to pip install it inside our Dockerfiles
